### ISSUE TITLE
Interfacing of ESP 8266 to cloud storage 

### ISSUE THREAD

**Issue by mikeshams** [stephybaby199/Capstone-project-summer2020#10]

**Comment by mikeshams** [comment]
1.	what issues did you or others might face when connecting the project to AWS platform?
2.	how to resolve them?

**Comment by Dixa2405** [comment]
when we did a research on free account for AWS that  has the limitation of uploading text only. for our project, we need to upload images to cloud storage. for accessing images to AWS we tried to get permission for an educational account but somehow our request got declined.
Also for uploading images we  need to make payment for every uploaded image. 
for a solution, we switched to Web server storage on which it was easy to upload images.its also free for unlimited storage.
