### ISSUE TITLE
Implementation On Circuit Design

### ISSUE THREAD

**Issue by mikeshams** [stephybaby199/Capstone-project-summer2020#2]

**Comment by mikeshams** [comment]
1. What issues did you face or others might face working with Easy EDA?
2. Did you install the software for Windows or Linux? What's the download link then?

**Comment by stephybaby199** [comment]
1. Issues I faced where some of my components symbols could not be found easily in the part library, but I was able to find it in the user-contributed library. some symbols or components may not be available so, we can create our own design and add it to the library.
2. I installed the software in windows. we can download and install it in Linux as well.
link to download in windows: https://easyeda.com/page/download
