### ISSUE TITLE
Install RTOS in Keil Software & Trying FreeRTOS working

### ISSUE THREAD

**Issue by mikeshams** [stephybaby199/Capstone-project-summer2020#3]

**Comment by mikeshams** [comment]
1. Why did you use Keil Software?

**Comment by stephybaby199** [comment]
Keil is a software development environment for ARM cortex-m based microcontrollers. it provides C/C++ compilers and an  integrated environment for RTOS. we are using LPC2148 in FreeRTOS. so keil software is perfect for our project. moreover, it is easy to use and work on it.
